### ISSUE TITLE
BeatTogether server crash

### ISSUE THREAD

**Issue by Goobwabber** [Goobwabber/BeatTogether.LiteNetLib#7]
```
Unhandled exception. Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'BeatTogether.LiteNetLib.Sources.UnconnectedMessageSource' while attempting to activate 'BeatTogether.LiteNetLib.Handlers.BroadcastPacketHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at BeatTogether.LiteNetLib.LiteNetServer.HandlePacket(EndPoint endPoint, ReadOnlySpan`1 buffer)
   at BeatTogether.LiteNetLib.LiteNetServer.OnReceived(EndPoint endPoint, Memory`1 buffer)
   at AsyncUdp.AsyncUdpServer.ProcessReceiveFrom(SocketAsyncEventArgs e)
   at AsyncUdp.AsyncUdpServer.TryReceive()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.InvalidOperationException: Unable to resolve service for type 'BeatTogether.LiteNetLib.Sources.UnconnectedMessageSource' while attempting to activate 'BeatTogether.LiteNetLib.Handlers.BroadcastPacketHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at BeatTogether.LiteNetLib.LiteNetServer.HandlePacket(EndPoint endPoint, ReadOnlySpan`1 buffer)
   at BeatTogether.LiteNetLib.LiteNetServer.OnReceived(EndPoint endPoint, Memory`1 buffer)
   at AsyncUdp.AsyncUdpServer.ProcessReceiveFrom(SocketAsyncEventArgs e)
   at AsyncUdp.AsyncUdpServer.TryReceive()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[02:42:40 INF] Dedicated node version: 1.1.1 starting: 199.195.251.114
[02:42:40 INF] Application started. Press Ctrl+C to shut down.
[02:42:40 INF] Hosting environment: Production
[02:42:40 INF] Content root path: /app
```

**Comment by cubicgraphics** [comment]
Unconnected messages should now be handled correctly

**Comment by cubicgraphics** [comment]
No longer a concern as lnl is no longer used
